import { readFileSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import type { MonitorForgeConfig } from '../config/schema.js';
import { resolveTheme } from '../theme/resolver.js';
import type { ApiTemplates } from '../../data/api-templates.schema.js';

export function generateManifests(config: MonitorForgeConfig): Record<string, string> {
  return {
    'source-manifest.ts': generateSourceManifest(config),
    'layer-manifest.ts': generateLayerManifest(config),
    'panel-manifest.ts': generatePanelManifest(config),
    'config-resolved.ts': generateResolvedConfig(config),
    'view-manifest.ts': generateViewManifest(config),
    'theme-resolved.ts': generateThemeManifest(config),
  };
}

function generateSourceManifest(config: MonitorForgeConfig): string {
  const imports = new Set<string>();
  const registrations: string[] = [];

  for (const source of config.sources) {
    switch (source.type) {
      case 'rss':
        imports.add("import { RSSSource } from '../core/sources/RSSSource.js';");
        break;
      case 'rest-api':
        imports.add("import { APISource } from '../core/sources/APISource.js';");
        break;
      case 'websocket':
        imports.add("import { WebSocketSource } from '../core/sources/WebSocketSource.js';");
        break;
    }
  }

  imports.add("import { registerSource } from '../core/sources/source-registry.js';");
  imports.add("import type { SourceConfig } from '../core/sources/SourceBase.js';");

  const sourceTypes = new Set(config.sources.map(s => s.type));
  if (sourceTypes.has('rss')) registrations.push("registerSource('rss', RSSSource);");
  if (sourceTypes.has('rest-api')) registrations.push("registerSource('rest-api', APISource);");
  if (sourceTypes.has('websocket')) registrations.push("registerSource('websocket', WebSocketSource);");

  return `// Auto-generated by forge build. Do not edit.
${Array.from(imports).join('\n')}

${registrations.join('\n')}

export const sourceConfigs: SourceConfig[] = ${JSON.stringify(config.sources.map(({ authEnvVar, ...rest }) => rest), null, 2)};
`;
}

function generateLayerManifest(config: MonitorForgeConfig): string {
  const layerTypes = new Set(config.layers.map(l => l.type));
  const imports: string[] = [
    "import { registerLayerType } from '../core/map/layer-registry.js';",
    "import type { LayerConfig } from '../core/map/LayerBase.js';",
  ];

  if (layerTypes.has('points')) {
    imports.push("import { PointsLayerPlugin } from '../core/map/layers/PointsLayer.js';");
  }
  if (layerTypes.has('lines')) {
    imports.push("import { LinesLayerPlugin } from '../core/map/layers/LinesLayer.js';");
  }
  if (layerTypes.has('polygons')) {
    imports.push("import { PolygonsLayerPlugin } from '../core/map/layers/PolygonsLayer.js';");
  }
  if (layerTypes.has('heatmap')) {
    imports.push("import { HeatmapLayerPlugin } from '../core/map/layers/HeatmapLayer.js';");
  }
  if (layerTypes.has('hexagon')) {
    imports.push("import { HexagonLayerPlugin } from '../core/map/layers/HexagonLayer.js';");
  }

  const registrations: string[] = [];
  if (layerTypes.has('points')) registrations.push("registerLayerType('points', PointsLayerPlugin);");
  if (layerTypes.has('lines')) registrations.push("registerLayerType('lines', LinesLayerPlugin);");
  if (layerTypes.has('polygons')) registrations.push("registerLayerType('polygons', PolygonsLayerPlugin);");
  if (layerTypes.has('heatmap')) registrations.push("registerLayerType('heatmap', HeatmapLayerPlugin);");
  if (layerTypes.has('hexagon')) registrations.push("registerLayerType('hexagon', HexagonLayerPlugin);");

  return `// Auto-generated by forge build. Do not edit.
${imports.join('\n')}

${registrations.join('\n')}

export const layerConfigs: LayerConfig[] = ${JSON.stringify(config.layers, null, 2)};
`;
}

function generatePanelManifest(config: MonitorForgeConfig): string {
  const panelTypes = new Set(config.panels.map(p => p.type));
  const imports: string[] = [
    "import { registerPanelType } from '../core/panels/panel-registry.js';",
    "import type { PanelConfig } from '../core/panels/PanelBase.js';",
  ];

  const typeMap: Record<string, string> = {
    'ai-brief': 'AIBriefPanel',
    'news-feed': 'NewsFeedPanel',
    'market-ticker': 'MarketTickerPanel',
    'entity-tracker': 'EntityTrackerPanel',
    'instability-index': 'InstabilityIndexPanel',
    'service-status': 'ServiceStatusPanel',
  };

  for (const type of panelTypes) {
    if (type !== 'custom' && typeMap[type]) {
      imports.push(`import { ${typeMap[type]} } from '../core/panels/types/${typeMap[type]}.js';`);
    }
  }

  const registrations: string[] = [];
  for (const type of panelTypes) {
    if (type !== 'custom' && typeMap[type]) {
      registrations.push(`registerPanelType('${type}', ${typeMap[type]});`);
    }
  }

  // Custom panels — import from src/custom-panels/ and register by panel name
  const customPanels = config.panels.filter(p => p.type === 'custom' && p.customModule);
  const seenModules = new Set<string>();
  for (const panel of customPanels) {
    const mod = panel.customModule!;
    if (!seenModules.has(mod)) {
      seenModules.add(mod);
      imports.push(`import { ${mod} } from '../custom-panels/${mod}.js';`);
    }
    registrations.push(`registerPanelType('${panel.name}', ${mod});`);
  }

  return `// Auto-generated by forge build. Do not edit.
${imports.join('\n')}

${registrations.join('\n')}

export const panelConfigs: PanelConfig[] = ${JSON.stringify(config.panels, null, 2)};
`;
}

export function generateProxyConfig(config: MonitorForgeConfig): string {
  const proxyEntries: Record<string, { envVar: string; header: string; scheme: 'bearer' | 'plain' }> = {};
  const ttlEntries: Record<string, number> = {};

  for (const source of config.sources) {
    // Build TTL map for all sources
    ttlEntries[source.name] = source.cacheTtl;

    // Build proxy auth config only for sources with authEnvVar
    if (source.authEnvVar) {
      try {
        const domain = new URL(source.url).hostname;
        const scheme = source.authHeader === 'Authorization' ? 'bearer' : 'plain';
        proxyEntries[domain] = {
          envVar: source.authEnvVar,
          header: source.authHeader,
          scheme,
        };
      } catch {
        // Skip invalid URLs (caught by schema validation)
      }
    }
  }

  return `// Auto-generated by forge build. Do not edit.
import type { ProxyAuthConfig } from './key-injection.js';

export const proxyConfig: Record<string, ProxyAuthConfig> = ${JSON.stringify(proxyEntries, null, 2)};

export const sourceTtl: Record<string, number> = ${JSON.stringify(ttlEntries, null, 2)};
`;
}

export function generateProxyAllowlist(config: MonitorForgeConfig): string {
  const domains = new Set<string>();

  // Extract hostnames from source URLs
  for (const source of config.sources) {
    try {
      domains.add(new URL(source.url).hostname);
    } catch {
      // Skip invalid URLs (caught by schema validation)
    }
  }

  // Extract hostnames from layer API URLs
  for (const layer of config.layers) {
    if (layer.data.source === 'api' && layer.data.url) {
      try {
        domains.add(new URL(layer.data.url).hostname);
      } catch {
        // Skip
      }
    }
  }

  // Add domains from proxy-required API templates
  try {
    const __filename = fileURLToPath(import.meta.url);
    const __dirname = dirname(__filename);
    const templatesPath = resolve(__dirname, '../../data/api-templates.json');
    const templates: ApiTemplates = JSON.parse(readFileSync(templatesPath, 'utf-8'));
    for (const template of templates.templates) {
      if (template.proxyRequired) {
        try {
          domains.add(new URL(template.baseUrl).hostname);
        } catch {
          // Skip invalid URLs
        }
      }
    }
  } catch {
    // API templates file not found — skip silently
  }

  // Merge explicitly configured allowedDomains (keep wildcard — isDomainAllowed handles it)
  for (const d of config.backend.corsProxy.allowedDomains) {
    domains.add(d);
  }

  const domainArray = Array.from(domains).sort();

  return `// Auto-generated by forge build. Do not edit.
export const PROXY_ALLOWED_DOMAINS: readonly string[] = ${JSON.stringify(domainArray, null, 2)};
export const CORS_ALLOWED_ORIGINS: readonly string[] = ${JSON.stringify(config.backend.corsProxy.corsOrigins, null, 2)};
`;
}

function generateViewManifest(config: MonitorForgeConfig): string {
  return `// Auto-generated by forge build. Do not edit.
export const viewConfigs = ${JSON.stringify(config.views ?? [], null, 2)};
`;
}

function generateResolvedConfig(config: MonitorForgeConfig): string {
  const clientConfig = {
    ...config,
    sources: config.sources.map(({ authEnvVar, ...rest }) => rest),
  };
  return `// Auto-generated by forge build. Do not edit.
import type { MonitorForgeConfig } from '../../forge/src/config/schema.js';

export const resolvedConfig: MonitorForgeConfig = ${JSON.stringify(clientConfig, null, 2)};
`;
}

function generateThemeManifest(config: MonitorForgeConfig): string {
  const theme = resolveTheme(config);
  return `// Auto-generated by forge build. Do not edit.
export const resolvedTheme = ${JSON.stringify(theme, null, 2)} as const;
`;
}
