import type { MonitorForgeConfig } from '../config/schema.js';

export function generateManifests(config: MonitorForgeConfig): Record<string, string> {
  return {
    'source-manifest.ts': generateSourceManifest(config),
    'layer-manifest.ts': generateLayerManifest(config),
    'panel-manifest.ts': generatePanelManifest(config),
    'config-resolved.ts': generateResolvedConfig(config),
  };
}

function generateSourceManifest(config: MonitorForgeConfig): string {
  const imports = new Set<string>();
  const registrations: string[] = [];

  for (const source of config.sources) {
    switch (source.type) {
      case 'rss':
        imports.add("import { RSSSource } from '../core/sources/RSSSource.js';");
        break;
      case 'rest-api':
        imports.add("import { APISource } from '../core/sources/APISource.js';");
        break;
      case 'websocket':
        imports.add("import { WebSocketSource } from '../core/sources/WebSocketSource.js';");
        break;
    }
  }

  imports.add("import { registerSource } from '../core/sources/source-registry.js';");

  registrations.push(
    "registerSource('rss', RSSSource);",
    "registerSource('rest-api', APISource);",
    "registerSource('websocket', WebSocketSource);",
  );

  return `// Auto-generated by forge build. Do not edit.
${Array.from(imports).join('\n')}

${registrations.join('\n')}

export const sourceConfigs = ${JSON.stringify(config.sources, null, 2)} as const;
`;
}

function generateLayerManifest(config: MonitorForgeConfig): string {
  const layerTypes = new Set(config.layers.map(l => l.type));
  const imports: string[] = [
    "import { registerLayerType } from '../core/map/layer-registry.js';",
  ];

  if (layerTypes.has('points')) {
    imports.push("import { PointsLayerPlugin } from '../core/map/layers/PointsLayer.js';");
  }
  if (layerTypes.has('lines')) {
    imports.push("import { LinesLayerPlugin } from '../core/map/layers/LinesLayer.js';");
  }
  if (layerTypes.has('polygons')) {
    imports.push("import { PolygonsLayerPlugin } from '../core/map/layers/PolygonsLayer.js';");
  }
  if (layerTypes.has('heatmap')) {
    imports.push("import { HeatmapLayerPlugin } from '../core/map/layers/HeatmapLayer.js';");
  }
  if (layerTypes.has('hexagon')) {
    imports.push("import { HexagonLayerPlugin } from '../core/map/layers/HexagonLayer.js';");
  }

  const registrations: string[] = [];
  if (layerTypes.has('points')) registrations.push("registerLayerType('points', PointsLayerPlugin);");
  if (layerTypes.has('lines')) registrations.push("registerLayerType('lines', LinesLayerPlugin);");
  if (layerTypes.has('polygons')) registrations.push("registerLayerType('polygons', PolygonsLayerPlugin);");
  if (layerTypes.has('heatmap')) registrations.push("registerLayerType('heatmap', HeatmapLayerPlugin);");
  if (layerTypes.has('hexagon')) registrations.push("registerLayerType('hexagon', HexagonLayerPlugin);");

  return `// Auto-generated by forge build. Do not edit.
${imports.join('\n')}

${registrations.join('\n')}

export const layerConfigs = ${JSON.stringify(config.layers, null, 2)} as const;
`;
}

function generatePanelManifest(config: MonitorForgeConfig): string {
  const panelTypes = new Set(config.panels.map(p => p.type));
  const imports: string[] = [
    "import { registerPanelType } from '../core/panels/panel-registry.js';",
  ];

  const typeMap: Record<string, string> = {
    'ai-brief': 'AIBriefPanel',
    'news-feed': 'NewsFeedPanel',
    'market-ticker': 'MarketTickerPanel',
    'entity-tracker': 'EntityTrackerPanel',
    'instability-index': 'InstabilityIndexPanel',
    'service-status': 'ServiceStatusPanel',
  };

  for (const type of panelTypes) {
    if (type !== 'custom' && typeMap[type]) {
      imports.push(`import { ${typeMap[type]} } from '../core/panels/types/${typeMap[type]}.js';`);
    }
  }

  const registrations: string[] = [];
  for (const type of panelTypes) {
    if (type !== 'custom' && typeMap[type]) {
      registrations.push(`registerPanelType('${type}', ${typeMap[type]});`);
    }
  }

  return `// Auto-generated by forge build. Do not edit.
${imports.join('\n')}

${registrations.join('\n')}

export const panelConfigs = ${JSON.stringify(config.panels, null, 2)} as const;
`;
}

function generateResolvedConfig(config: MonitorForgeConfig): string {
  return `// Auto-generated by forge build. Do not edit.
import type { MonitorForgeConfig } from '../../forge/src/config/schema.js';

export const resolvedConfig: MonitorForgeConfig = ${JSON.stringify(config, null, 2)};
`;
}
