import { describe, it, expect } from 'vitest';
import { generateManifests } from './manifest-generator.js';
import type { MonitorForgeConfig } from '../config/schema.js';

function buildConfig(overrides?: Partial<MonitorForgeConfig>): MonitorForgeConfig {
  return {
    monitor: { name: 'Test', slug: 'test', description: '', domain: 'test', tags: [], branding: { primaryColor: '#0052CC' } },
    sources: [], layers: [], panels: [],
    ai: { enabled: false, fallbackChain: [], providers: {}, analysis: { summarization: true, entityExtraction: true, sentimentAnalysis: true, focalPointDetection: false } },
    map: { style: 'https://example.com/style.json', center: [0, 0], zoom: 3, minZoom: 2, maxZoom: 18, projection: 'mercator', dayNightOverlay: false },
    backend: { cache: { provider: 'memory', ttlSeconds: 300 }, rateLimit: { enabled: true, maxRequests: 100, windowSeconds: 60 }, corsProxy: { enabled: true, allowedDomains: ['*'] } },
    build: { target: 'vercel', outDir: 'dist' },
    ...overrides,
  };
}

describe('generateManifests', () => {
  it('returns 4 manifest files', () => {
    const result = generateManifests(buildConfig());
    expect(Object.keys(result)).toEqual([
      'source-manifest.ts',
      'layer-manifest.ts',
      'panel-manifest.ts',
      'config-resolved.ts',
    ]);
  });

  describe('source manifest', () => {
    it('imports RSSSource when RSS sources present', () => {
      const config = buildConfig({
        sources: [{ name: 'rss-feed', type: 'rss', url: 'https://example.com/rss', category: 'news', tier: 3, interval: 300, language: 'en', tags: [] }],
      });
      const manifest = generateManifests(config)['source-manifest.ts'];
      expect(manifest).toContain("import { RSSSource }");
      expect(manifest).toContain("registerSource('rss', RSSSource)");
    });

    it('imports APISource when rest-api sources present', () => {
      const config = buildConfig({
        sources: [{ name: 'api-feed', type: 'rest-api', url: 'https://example.com/api', category: 'data', tier: 3, interval: 300, language: 'en', tags: [] }],
      });
      const manifest = generateManifests(config)['source-manifest.ts'];
      expect(manifest).toContain("import { APISource }");
      expect(manifest).toContain("registerSource('rest-api', APISource)");
    });

    it('imports WebSocketSource when websocket sources present', () => {
      const config = buildConfig({
        sources: [{ name: 'ws-feed', type: 'websocket', url: 'wss://example.com/ws', category: 'live', tier: 3, interval: 300, language: 'en', tags: [] }],
      });
      const manifest = generateManifests(config)['source-manifest.ts'];
      expect(manifest).toContain("import { WebSocketSource }");
      expect(manifest).toContain("registerSource('websocket', WebSocketSource)");
    });

    it('does not import unused source types', () => {
      const config = buildConfig({
        sources: [{ name: 'rss-only', type: 'rss', url: 'https://example.com/rss', category: 'news', tier: 3, interval: 300, language: 'en', tags: [] }],
      });
      const manifest = generateManifests(config)['source-manifest.ts'];
      expect(manifest).not.toContain('APISource');
      expect(manifest).not.toContain('WebSocketSource');
    });

    it('does not register unused source types', () => {
      const config = buildConfig({
        sources: [{ name: 'rss-only', type: 'rss', url: 'https://example.com/rss', category: 'news', tier: 3, interval: 300, language: 'en', tags: [] }],
      });
      const manifest = generateManifests(config)['source-manifest.ts'];
      expect(manifest).not.toContain("registerSource('rest-api'");
      expect(manifest).not.toContain("registerSource('websocket'");
    });

    it('includes sourceConfigs export with correct JSON', () => {
      const config = buildConfig({
        sources: [{ name: 'test', type: 'rss', url: 'https://example.com/rss', category: 'news', tier: 3, interval: 300, language: 'en', tags: [] }],
      });
      const manifest = generateManifests(config)['source-manifest.ts'];
      expect(manifest).toContain('export const sourceConfigs');
      expect(manifest).toContain('"name": "test"');
    });

    it('includes auto-generated header comment', () => {
      const manifest = generateManifests(buildConfig())['source-manifest.ts'];
      expect(manifest).toContain('Auto-generated by forge build');
    });

    it('handles empty sources array', () => {
      const manifest = generateManifests(buildConfig())['source-manifest.ts'];
      expect(manifest).toContain('export const sourceConfigs = []');
      expect(manifest).not.toContain('RSSSource');
    });
  });

  describe('layer manifest', () => {
    it('imports only the layer plugins used', () => {
      const config = buildConfig({
        layers: [{ name: 'pts', type: 'points', displayName: 'P', color: '#FF0000', data: { source: 'static', path: 'f.geojson' }, defaultVisible: false, category: 'c' }],
      });
      const manifest = generateManifests(config)['layer-manifest.ts'];
      expect(manifest).toContain('PointsLayerPlugin');
      expect(manifest).not.toContain('LinesLayerPlugin');
      expect(manifest).not.toContain('HeatmapLayerPlugin');
    });

    it('generates registration calls for each used type', () => {
      const config = buildConfig({
        layers: [
          { name: 'pts', type: 'points', displayName: 'P', color: '#FF0000', data: { source: 'static', path: 'f.geojson' }, defaultVisible: false, category: 'c' },
          { name: 'lines', type: 'lines', displayName: 'L', color: '#00FF00', data: { source: 'static', path: 'l.geojson' }, defaultVisible: false, category: 'c' },
        ],
      });
      const manifest = generateManifests(config)['layer-manifest.ts'];
      expect(manifest).toContain("registerLayerType('points'");
      expect(manifest).toContain("registerLayerType('lines'");
    });

    it('handles empty layers array', () => {
      const manifest = generateManifests(buildConfig())['layer-manifest.ts'];
      expect(manifest).toContain('export const layerConfigs = []');
      expect(manifest).not.toContain('PointsLayerPlugin');
    });
  });

  describe('panel manifest', () => {
    it('imports panel types used in config', () => {
      const config = buildConfig({
        panels: [{ name: 'feed', type: 'news-feed', displayName: 'News', position: 0, config: {} }],
      });
      const manifest = generateManifests(config)['panel-manifest.ts'];
      expect(manifest).toContain('NewsFeedPanel');
      expect(manifest).toContain("registerPanelType('news-feed'");
    });

    it('excludes custom type from imports', () => {
      const config = buildConfig({
        panels: [{ name: 'custom-panel', type: 'custom', displayName: 'Custom', position: 0, config: {} }],
      });
      const manifest = generateManifests(config)['panel-manifest.ts'];
      expect(manifest).not.toContain('import { Custom');
      expect(manifest).not.toContain("registerPanelType('custom'");
    });

    it('handles empty panels array', () => {
      const manifest = generateManifests(buildConfig())['panel-manifest.ts'];
      expect(manifest).toContain('export const panelConfigs = []');
    });
  });

  describe('config-resolved manifest', () => {
    it('exports full config as JSON', () => {
      const config = buildConfig();
      const manifest = generateManifests(config)['config-resolved.ts'];
      expect(manifest).toContain('export const resolvedConfig');
      expect(manifest).toContain('"name": "Test"');
    });

    it('includes type annotation', () => {
      const manifest = generateManifests(buildConfig())['config-resolved.ts'];
      expect(manifest).toContain('MonitorForgeConfig');
    });
  });

  // ──────────────────────────────────────────────────────────────
  // Structural Integrity Tests
  // ──────────────────────────────────────────────────────────────

  describe('generated code structural integrity', () => {
    // Helper: extract all "import { ClassName }" identifiers from generated code
    function extractImportedClasses(code: string): string[] {
      const matches = [...code.matchAll(/import\s*\{\s*(\w+)\s*\}/g)];
      return matches.map(m => m[1]);
    }

    // Helper: extract all class names from registration calls
    function extractRegisteredClasses(code: string): string[] {
      const matches = [...code.matchAll(/register\w+\([^,]+,\s*(\w+)\)/g)];
      return matches.map(m => m[1]);
    }

    // Helper: extract the JSON array from "export const xxxConfigs = [...] as const;"
    function extractExportedJson(code: string, varName: string): unknown[] {
      const match = code.match(new RegExp(`export const ${varName} = (\\[[\\s\\S]*?\\]) as const;`));
      if (!match) throw new Error(`Could not extract ${varName} from generated code`);
      return JSON.parse(match[1]);
    }

    // Source manifest: import/registration matching
    it('source manifest: every imported class has a corresponding registration', () => {
      const config = buildConfig({
        sources: [
          { name: 'r', type: 'rss', url: 'https://a.com/rss', category: 'n', tier: 3, interval: 300, language: 'en', tags: [] },
          { name: 'a', type: 'rest-api', url: 'https://b.com/api', category: 'd', tier: 3, interval: 300, language: 'en', tags: [] },
        ],
      });
      const code = generateManifests(config)['source-manifest.ts'];
      const imported = extractImportedClasses(code).filter(c => c !== 'registerSource');
      const registered = extractRegisteredClasses(code);
      // Every imported class must be registered
      for (const cls of imported) {
        expect(registered).toContain(cls);
      }
      // Every registered class must be imported
      for (const cls of registered) {
        expect(imported).toContain(cls);
      }
    });

    it('layer manifest: every imported plugin has a corresponding registration', () => {
      const config = buildConfig({
        layers: [
          { name: 'p', type: 'points', displayName: 'P', color: '#FF0000', data: { source: 'static', path: 'f.geojson' }, defaultVisible: false, category: 'c' },
          { name: 'h', type: 'heatmap', displayName: 'H', color: '#00FF00', data: { source: 'static', path: 'h.geojson' }, defaultVisible: false, category: 'c' },
        ],
      });
      const code = generateManifests(config)['layer-manifest.ts'];
      const imported = extractImportedClasses(code).filter(c => c !== 'registerLayerType');
      const registered = extractRegisteredClasses(code);
      for (const cls of imported) {
        expect(registered).toContain(cls);
      }
      for (const cls of registered) {
        expect(imported).toContain(cls);
      }
    });

    it('panel manifest: every imported panel has a corresponding registration', () => {
      const config = buildConfig({
        panels: [
          { name: 'f', type: 'news-feed', displayName: 'F', position: 0, config: {} },
          { name: 'a', type: 'ai-brief', displayName: 'A', position: 1, config: {} },
        ],
      });
      const code = generateManifests(config)['panel-manifest.ts'];
      const imported = extractImportedClasses(code).filter(c => c !== 'registerPanelType');
      const registered = extractRegisteredClasses(code);
      for (const cls of imported) {
        expect(registered).toContain(cls);
      }
      for (const cls of registered) {
        expect(imported).toContain(cls);
      }
    });

    // Deduplication: multiple sources of same type → 1 import, 1 registration
    it('deduplicates imports for multiple RSS sources', () => {
      const config = buildConfig({
        sources: [
          { name: 'rss-1', type: 'rss', url: 'https://a.com/rss', category: 'n', tier: 3, interval: 300, language: 'en', tags: [] },
          { name: 'rss-2', type: 'rss', url: 'https://b.com/rss', category: 'n', tier: 3, interval: 300, language: 'en', tags: [] },
          { name: 'rss-3', type: 'rss', url: 'https://c.com/rss', category: 'n', tier: 3, interval: 300, language: 'en', tags: [] },
        ],
      });
      const code = generateManifests(config)['source-manifest.ts'];
      const rssImportCount = (code.match(/import \{ RSSSource \}/g) ?? []).length;
      const rssRegCount = (code.match(/registerSource\('rss'/g) ?? []).length;
      expect(rssImportCount).toBe(1);
      expect(rssRegCount).toBe(1);
    });

    it('deduplicates imports for multiple points layers', () => {
      const config = buildConfig({
        layers: [
          { name: 'p1', type: 'points', displayName: 'P1', color: '#FF0000', data: { source: 'static', path: 'a.geojson' }, defaultVisible: false, category: 'c' },
          { name: 'p2', type: 'points', displayName: 'P2', color: '#00FF00', data: { source: 'static', path: 'b.geojson' }, defaultVisible: false, category: 'c' },
        ],
      });
      const code = generateManifests(config)['layer-manifest.ts'];
      const importCount = (code.match(/import \{ PointsLayerPlugin \}/g) ?? []).length;
      const regCount = (code.match(/registerLayerType\('points'/g) ?? []).length;
      expect(importCount).toBe(1);
      expect(regCount).toBe(1);
    });

    // All types simultaneously
    it('handles all 3 source types simultaneously', () => {
      const config = buildConfig({
        sources: [
          { name: 'r', type: 'rss', url: 'https://a.com/rss', category: 'n', tier: 3, interval: 300, language: 'en', tags: [] },
          { name: 'a', type: 'rest-api', url: 'https://b.com/api', category: 'd', tier: 3, interval: 300, language: 'en', tags: [] },
          { name: 'w', type: 'websocket', url: 'wss://c.com/ws', category: 'l', tier: 3, interval: 300, language: 'en', tags: [] },
        ],
      });
      const code = generateManifests(config)['source-manifest.ts'];
      expect(code).toContain('RSSSource');
      expect(code).toContain('APISource');
      expect(code).toContain('WebSocketSource');
      const registered = extractRegisteredClasses(code);
      expect(registered).toHaveLength(3);
    });

    it('handles all 5 layer types simultaneously', () => {
      const makeLayer = (name: string, type: string) => ({
        name, type: type as any, displayName: name, color: '#FF0000',
        data: { source: 'static' as const, path: `${name}.geojson` }, defaultVisible: false, category: 'c',
      });
      const config = buildConfig({
        layers: [
          makeLayer('pts', 'points'), makeLayer('lin', 'lines'), makeLayer('pol', 'polygons'),
          makeLayer('hm', 'heatmap'), makeLayer('hex', 'hexagon'),
        ],
      });
      const code = generateManifests(config)['layer-manifest.ts'];
      const registered = extractRegisteredClasses(code);
      expect(registered).toHaveLength(5);
      expect(code).toContain('PointsLayerPlugin');
      expect(code).toContain('LinesLayerPlugin');
      expect(code).toContain('PolygonsLayerPlugin');
      expect(code).toContain('HeatmapLayerPlugin');
      expect(code).toContain('HexagonLayerPlugin');
    });

    it('handles all 6 built-in panel types simultaneously', () => {
      const types = ['ai-brief', 'news-feed', 'market-ticker', 'entity-tracker', 'instability-index', 'service-status'] as const;
      const config = buildConfig({
        panels: types.map((type, i) => ({ name: `p${i}`, type, displayName: `P${i}`, position: i, config: {} })),
      });
      const code = generateManifests(config)['panel-manifest.ts'];
      const registered = extractRegisteredClasses(code);
      expect(registered).toHaveLength(6);
      expect(code).toContain('AIBriefPanel');
      expect(code).toContain('NewsFeedPanel');
      expect(code).toContain('MarketTickerPanel');
      expect(code).toContain('EntityTrackerPanel');
      expect(code).toContain('InstabilityIndexPanel');
      expect(code).toContain('ServiceStatusPanel');
    });

    // Exported JSON is parseable and correct
    it('sourceConfigs export contains valid parseable JSON matching config', () => {
      const sources = [
        { name: 'alpha', type: 'rss' as const, url: 'https://a.com/rss', category: 'news', tier: 3, interval: 300, language: 'en', tags: [] },
        { name: 'beta', type: 'rest-api' as const, url: 'https://b.com/api', category: 'data', tier: 2, interval: 60, language: 'ko', tags: ['tech'] },
      ];
      const config = buildConfig({ sources });
      const code = generateManifests(config)['source-manifest.ts'];
      const parsed = extractExportedJson(code, 'sourceConfigs') as Array<{ name: string }>;
      expect(parsed).toHaveLength(2);
      expect(parsed[0].name).toBe('alpha');
      expect(parsed[1].name).toBe('beta');
    });

    it('layerConfigs export contains valid parseable JSON matching config', () => {
      const layers = [
        { name: 'events', type: 'points' as const, displayName: 'Events', color: '#FF0000', data: { source: 'static' as const, path: 'events.geojson' }, defaultVisible: false, category: 'c' },
      ];
      const config = buildConfig({ layers });
      const code = generateManifests(config)['layer-manifest.ts'];
      const parsed = extractExportedJson(code, 'layerConfigs') as Array<{ name: string }>;
      expect(parsed).toHaveLength(1);
      expect(parsed[0].name).toBe('events');
    });

    it('panelConfigs export contains valid parseable JSON matching config', () => {
      const panels = [
        { name: 'feed', type: 'news-feed' as const, displayName: 'News', position: 0, config: {} },
        { name: 'brief', type: 'ai-brief' as const, displayName: 'AI', position: 1, config: {} },
      ];
      const config = buildConfig({ panels });
      const code = generateManifests(config)['panel-manifest.ts'];
      const parsed = extractExportedJson(code, 'panelConfigs') as Array<{ name: string }>;
      expect(parsed).toHaveLength(2);
      expect(parsed.map(p => p.name)).toEqual(['feed', 'brief']);
    });

    // as const suffix
    it('config arrays end with "as const"', () => {
      const config = buildConfig({
        sources: [{ name: 'r', type: 'rss', url: 'https://a.com/rss', category: 'n', tier: 3, interval: 300, language: 'en', tags: [] }],
        layers: [{ name: 'p', type: 'points', displayName: 'P', color: '#FF0000', data: { source: 'static', path: 'f.geojson' }, defaultVisible: false, category: 'c' }],
        panels: [{ name: 'f', type: 'news-feed', displayName: 'F', position: 0, config: {} }],
      });
      const manifests = generateManifests(config);
      expect(manifests['source-manifest.ts']).toMatch(/sourceConfigs = \[[\s\S]*?\] as const;/);
      expect(manifests['layer-manifest.ts']).toMatch(/layerConfigs = \[[\s\S]*?\] as const;/);
      expect(manifests['panel-manifest.ts']).toMatch(/panelConfigs = \[[\s\S]*?\] as const;/);
    });
  });

  // ──────────────────────────────────────────────────────────────
  // Config-to-Code Contract Tests
  // ──────────────────────────────────────────────────────────────

  describe('config-to-code contract', () => {
    function extractExportedJson(code: string, varName: string): unknown[] {
      const match = code.match(new RegExp(`export const ${varName} = (\\[[\\s\\S]*?\\]) as const;`));
      if (!match) throw new Error(`Could not extract ${varName}`);
      return JSON.parse(match[1]);
    }

    it('every source in config appears in generated sourceConfigs with all fields', () => {
      const sources = [
        { name: 'feed-a', type: 'rss' as const, url: 'https://a.com/rss', category: 'news', tier: 1, interval: 60, language: 'ko', tags: ['urgent', 'breaking'] },
        { name: 'api-b', type: 'rest-api' as const, url: 'https://b.com/api', category: 'data', tier: 4, interval: 600, language: 'en', tags: [] },
        { name: 'ws-c', type: 'websocket' as const, url: 'wss://c.com/ws', category: 'live', tier: 2, interval: 10, language: 'ja', tags: ['realtime'] },
      ];
      const config = buildConfig({ sources });
      const code = generateManifests(config)['source-manifest.ts'];
      const parsed = extractExportedJson(code, 'sourceConfigs') as typeof sources;
      expect(parsed).toHaveLength(3);
      // Verify every field is preserved
      for (let i = 0; i < sources.length; i++) {
        expect(parsed[i].name).toBe(sources[i].name);
        expect(parsed[i].type).toBe(sources[i].type);
        expect(parsed[i].url).toBe(sources[i].url);
        expect(parsed[i].tier).toBe(sources[i].tier);
        expect(parsed[i].interval).toBe(sources[i].interval);
        expect(parsed[i].language).toBe(sources[i].language);
        expect(parsed[i].tags).toEqual(sources[i].tags);
      }
    });

    it('preserves special characters in URL query strings', () => {
      const config = buildConfig({
        sources: [{
          name: 'complex-url', type: 'rss',
          url: 'https://example.com/rss?key=value&lang=ko&q=hello+world',
          category: 'news', tier: 3, interval: 300, language: 'en', tags: [],
        }],
      });
      const code = generateManifests(config)['source-manifest.ts'];
      const parsed = extractExportedJson(code, 'sourceConfigs') as Array<{ url: string }>;
      expect(parsed[0].url).toBe('https://example.com/rss?key=value&lang=ko&q=hello+world');
    });

    it('preserves unicode characters in category and tags', () => {
      const config = buildConfig({
        sources: [{
          name: 'unicode-src', type: 'rss',
          url: 'https://example.com/rss',
          category: '기술', tier: 3, interval: 300, language: 'ko', tags: ['뉴스', 'テック'],
        }],
      });
      const code = generateManifests(config)['source-manifest.ts'];
      const parsed = extractExportedJson(code, 'sourceConfigs') as Array<{ category: string; tags: string[] }>;
      expect(parsed[0].category).toBe('기술');
      expect(parsed[0].tags).toEqual(['뉴스', 'テック']);
    });

    it('config-resolved roundtrips the full config object', () => {
      const config = buildConfig({
        sources: [{ name: 'r', type: 'rss', url: 'https://a.com/rss', category: 'n', tier: 3, interval: 300, language: 'en', tags: [] }],
        layers: [{ name: 'p', type: 'points', displayName: 'P', color: '#FF0000', data: { source: 'static', path: 'f.geojson' }, defaultVisible: false, category: 'c' }],
        panels: [{ name: 'f', type: 'news-feed', displayName: 'F', position: 0, config: {} }],
      });
      const code = generateManifests(config)['config-resolved.ts'];
      // Extract the JSON object from the generated code
      const match = code.match(/export const resolvedConfig:\s*MonitorForgeConfig\s*=\s*({[\s\S]*});/);
      expect(match).not.toBeNull();
      const parsed = JSON.parse(match![1]);
      expect(parsed.monitor.name).toBe('Test');
      expect(parsed.sources).toHaveLength(1);
      expect(parsed.sources[0].name).toBe('r');
      expect(parsed.layers).toHaveLength(1);
      expect(parsed.panels).toHaveLength(1);
    });

    it('preserves optional source fields like headers and transform', () => {
      const config = buildConfig({
        sources: [{
          name: 'with-opts', type: 'rest-api',
          url: 'https://api.com/v1',
          category: 'data', tier: 3, interval: 300, language: 'en', tags: [],
          headers: { 'X-Api-Key': '${env.MY_KEY}', 'Accept': 'application/json' },
          transform: 'data.results',
        }],
      });
      const code = generateManifests(config)['source-manifest.ts'];
      const parsed = extractExportedJson(code, 'sourceConfigs') as Array<{ headers: Record<string, string>; transform: string }>;
      expect(parsed[0].headers).toEqual({ 'X-Api-Key': '${env.MY_KEY}', 'Accept': 'application/json' });
      expect(parsed[0].transform).toBe('data.results');
    });

    it('preserves layer data fields for all source types', () => {
      const config = buildConfig({
        layers: [
          { name: 'static-l', type: 'points', displayName: 'S', color: '#FF0000', data: { source: 'static', path: 'data/geo/events.geojson' }, defaultVisible: true, category: 'c' },
          { name: 'api-l', type: 'lines', displayName: 'A', color: '#00FF00', data: { source: 'api', url: 'https://api.com/geo' }, defaultVisible: false, category: 'c' },
          { name: 'ref-l', type: 'polygons', displayName: 'R', color: '#0000FF', data: { source: 'source-ref', sourceRef: 'my-api' }, defaultVisible: false, category: 'c' },
        ],
      });
      const code = generateManifests(config)['layer-manifest.ts'];
      const parsed = extractExportedJson(code, 'layerConfigs') as Array<{ name: string; data: Record<string, string> }>;
      expect(parsed[0].data.source).toBe('static');
      expect(parsed[0].data.path).toBe('data/geo/events.geojson');
      expect(parsed[1].data.source).toBe('api');
      expect(parsed[1].data.url).toBe('https://api.com/geo');
      expect(parsed[2].data.source).toBe('source-ref');
      expect(parsed[2].data.sourceRef).toBe('my-api');
    });

    it('preserves panel config object contents', () => {
      const config = buildConfig({
        panels: [{
          name: 'configured', type: 'news-feed', displayName: 'News', position: 0,
          config: { maxItems: 50, showImages: true, source: 'my-rss' },
        }],
      });
      const code = generateManifests(config)['panel-manifest.ts'];
      const parsed = extractExportedJson(code, 'panelConfigs') as Array<{ config: Record<string, unknown> }>;
      expect(parsed[0].config).toEqual({ maxItems: 50, showImages: true, source: 'my-rss' });
    });
  });
});
