import { MapEngine, type MapConfig } from './core/map/MapEngine.js';
import { PanelManager, type ViewConfig } from './core/panels/PanelManager.js';
import { SourceManager } from './core/sources/SourceManager.js';
import type { SourceHealth } from './core/sources/SourceHealth.js';
import { AIManager, type AIConfig } from './core/ai/AIManager.js';
import { IdleDetector } from './core/ui/IdleDetector.js';
import './styles/base.css';
import './styles/animations.css';
import './styles/views.css';

export class App {
  private root: HTMLElement;
  private mapEngine: MapEngine | null = null;
  private panelManager: PanelManager | null = null;
  private sourceManager: SourceManager | null = null;
  private aiManager: AIManager | null = null;
  private idleDetector: IdleDetector | null = null;

  constructor(root: HTMLElement) {
    this.root = root;
  }

  async initialize(): Promise<void> {
    // Load resolved config (generated by forge build)
    const { resolvedConfig: config } = await import('./generated/config-resolved.js');

    // Build layout
    this.root.innerHTML = `
      <header class="forge-header">
        <h1 class="forge-title">${config.monitor.name}</h1>
        <div class="forge-header-actions">
          <span id="forge-health-indicator" class="forge-health-indicator" style="display:none">
            <span class="forge-health-dot"></span>
            <span class="forge-health-text"></span>
          </span>
          <button id="layer-toggle-btn" class="forge-btn">Layers</button>
        </div>
      </header>
      <main class="forge-main">
        <div class="forge-map-container" id="forge-map"></div>
        <aside class="forge-sidebar" id="forge-sidebar"></aside>
      </main>
      <div class="forge-layer-panel hidden" id="forge-layer-panel"></div>
    `;

    // Initialize source manager
    await import('./generated/source-manifest.js');
    const { sourceConfigs } = await import('./generated/source-manifest.js');
    this.sourceManager = new SourceManager();
    this.sourceManager.initialize(sourceConfigs);

    // Initialize map
    const mapContainer = document.getElementById('forge-map')!;
    this.mapEngine = new MapEngine(mapContainer, config.map as MapConfig);
    await this.mapEngine.initialize();

    // Load layers
    await import('./generated/layer-manifest.js');
    const { layerConfigs } = await import('./generated/layer-manifest.js');
    for (const layerConfig of layerConfigs) {
      await this.mapEngine.addLayer(layerConfig);
    }

    // Initialize panels and views
    await import('./generated/panel-manifest.js');
    const { panelConfigs } = await import('./generated/panel-manifest.js');
    const { viewConfigs } = await import('./generated/view-manifest.js');
    const sidebar = document.getElementById('forge-sidebar')!;
    this.panelManager = new PanelManager(sidebar);
    const views = (viewConfigs as ViewConfig[]).length > 0 ? viewConfigs as ViewConfig[] : undefined;
    this.panelManager.initialize(panelConfigs, views);

    // Render view tabs if views are defined
    if (views) {
      this.renderViewTabs(views);
      this.panelManager.onViewChange((viewName) => {
        document.querySelectorAll('.forge-view-tab').forEach(t => {
          const el = t as HTMLElement;
          const active = el.dataset.view === viewName;
          el.classList.toggle('active', active);
          el.setAttribute('aria-selected', String(active));
        });
      });
    }

    // Initialize AI
    this.aiManager = new AIManager(config.ai as AIConfig);

    // Wire up source updates to panels
    this.sourceManager.onItems((items) => {
      this.panelManager?.updateAll(items);
    });

    // Wire up source health to service-status panel and header indicator
    this.sourceManager.onHealth((health) => {
      this.panelManager?.updatePanel('service-status', health);
      this.updateHealthIndicator(health);
    });

    // Layer toggle button
    const layerBtn = document.getElementById('layer-toggle-btn')!;
    const layerPanel = document.getElementById('forge-layer-panel')!;
    layerBtn.addEventListener('click', () => {
      layerPanel.classList.toggle('hidden');
      this.renderLayerPanel(layerPanel);
    });

    // Idle detection — pause animations when inactive
    this.idleDetector = new IdleDetector();

    // Start fetching data
    this.sourceManager.startAll();

    // Initial AI brief
    if (this.aiManager.isEnabled()) {
      this.generateAIBrief();
    }
  }

  private renderViewTabs(views: ViewConfig[]): void {
    const headerActions = document.querySelector('.forge-header-actions');
    if (!headerActions) return;

    const tabContainer = document.createElement('div');
    tabContainer.className = 'forge-view-tabs';
    tabContainer.setAttribute('role', 'tablist');
    tabContainer.setAttribute('aria-label', 'Dashboard views');

    for (let i = 0; i < views.length; i++) {
      const view = views[i];
      const isActive = this.panelManager?.getActiveView() === view.name;

      const tab = document.createElement('button');
      tab.className = 'forge-view-tab';
      tab.dataset.view = view.name;
      tab.id = `forge-view-tab-${view.name}`;
      tab.textContent = view.icon ? `${view.icon} ${view.displayName}` : view.displayName;
      tab.title = `${view.displayName} (press ${i + 1})`;
      tab.setAttribute('role', 'tab');
      tab.setAttribute('aria-selected', String(isActive));
      tab.setAttribute('aria-controls', `forge-view-${view.name}`);

      if (isActive) {
        tab.classList.add('active');
      }

      tab.addEventListener('click', () => {
        this.panelManager?.switchView(view.name);
      });

      tabContainer.appendChild(tab);
    }

    headerActions.insertBefore(tabContainer, headerActions.firstChild);
  }

  private async generateAIBrief(): Promise<void> {
    if (!this.sourceManager || !this.aiManager) return;
    try {
      const items = await this.sourceManager.fetchAll();
      const brief = await this.aiManager.generateBrief(items);
      this.panelManager?.updatePanel('ai-insights', {
        summary: brief,
        timestamp: new Date().toISOString(),
      });
    } catch (err) {
      console.warn('AI brief generation failed:', err);
    }
  }

  private renderLayerPanel(container: HTMLElement): void {
    if (!this.mapEngine) return;
    const layers = this.mapEngine.getLayerConfigs();

    container.innerHTML = `
      <div class="layer-panel-content">
        <h3>Map Layers</h3>
        ${layers.map(l => `
          <label class="layer-toggle">
            <input type="checkbox" ${l.visible ? 'checked' : ''} data-layer="${l.name}">
            <span>${l.displayName}</span>
          </label>
        `).join('')}
      </div>
    `;

    container.querySelectorAll('input[data-layer]').forEach(input => {
      input.addEventListener('change', (e) => {
        const target = e.target as HTMLInputElement;
        this.mapEngine?.toggleLayer(target.dataset.layer!, target.checked);
      });
    });
  }

  private updateHealthIndicator(health: Map<string, SourceHealth>): void {
    const indicator = document.getElementById('forge-health-indicator');
    if (!indicator) return;

    const entries = Array.from(health.values());
    const offline = entries.filter(h => h.status === 'offline').length;
    const degraded = entries.filter(h => h.status === 'degraded').length;

    if (offline === 0 && degraded === 0) {
      indicator.style.display = 'none';
      return;
    }

    indicator.style.display = 'inline-flex';
    const dot = indicator.querySelector('.forge-health-dot') as HTMLElement;
    const text = indicator.querySelector('.forge-health-text') as HTMLElement;

    const parts: string[] = [];
    if (offline > 0) parts.push(`${offline} offline`);
    if (degraded > 0) parts.push(`${degraded} degraded`);

    dot.className = offline > 0
      ? 'forge-health-dot status-red'
      : 'forge-health-dot status-yellow';
    text.textContent = parts.join(', ');
  }

  destroy(): void {
    this.sourceManager?.stopAll();
    this.panelManager?.destroy();
    this.mapEngine?.destroy();
    this.idleDetector?.destroy();
  }
}
