import { MapEngine, type MapConfig } from './core/map/MapEngine.js';
import { PanelManager } from './core/panels/PanelManager.js';
import { SourceManager } from './core/sources/SourceManager.js';
import { AIManager, type AIConfig } from './core/ai/AIManager.js';
import './styles/base.css';

export class App {
  private root: HTMLElement;
  private mapEngine: MapEngine | null = null;
  private panelManager: PanelManager | null = null;
  private sourceManager: SourceManager | null = null;
  private aiManager: AIManager | null = null;

  constructor(root: HTMLElement) {
    this.root = root;
  }

  async initialize(): Promise<void> {
    // Load resolved config (generated by forge build)
    const { resolvedConfig: config } = await import('./generated/config-resolved.js');

    // Build layout
    this.root.innerHTML = `
      <header class="forge-header">
        <h1 class="forge-title">${config.monitor.name}</h1>
        <div class="forge-header-actions">
          <button id="layer-toggle-btn" class="forge-btn">Layers</button>
        </div>
      </header>
      <main class="forge-main">
        <div class="forge-map-container" id="forge-map"></div>
        <aside class="forge-sidebar" id="forge-sidebar"></aside>
      </main>
      <div class="forge-layer-panel hidden" id="forge-layer-panel"></div>
    `;

    // Initialize source manager
    await import('./generated/source-manifest.js');
    const { sourceConfigs } = await import('./generated/source-manifest.js');
    this.sourceManager = new SourceManager();
    this.sourceManager.initialize(sourceConfigs as any[]);

    // Initialize map
    const mapContainer = document.getElementById('forge-map')!;
    this.mapEngine = new MapEngine(mapContainer, config.map as MapConfig);
    await this.mapEngine.initialize();

    // Load layers
    await import('./generated/layer-manifest.js');
    const { layerConfigs } = await import('./generated/layer-manifest.js');
    for (const layerConfig of layerConfigs) {
      await this.mapEngine.addLayer(layerConfig as any);
    }

    // Initialize panels
    await import('./generated/panel-manifest.js');
    const { panelConfigs } = await import('./generated/panel-manifest.js');
    const sidebar = document.getElementById('forge-sidebar')!;
    this.panelManager = new PanelManager(sidebar);
    this.panelManager.initialize(panelConfigs as any[]);

    // Initialize AI
    this.aiManager = new AIManager(config.ai as AIConfig);

    // Wire up source updates to panels
    this.sourceManager.onItems((items) => {
      this.panelManager?.updateAll(items);
    });

    // Layer toggle button
    const layerBtn = document.getElementById('layer-toggle-btn')!;
    const layerPanel = document.getElementById('forge-layer-panel')!;
    layerBtn.addEventListener('click', () => {
      layerPanel.classList.toggle('hidden');
      this.renderLayerPanel(layerPanel);
    });

    // Start fetching data
    this.sourceManager.startAll();

    // Initial AI brief
    if (this.aiManager.isEnabled()) {
      this.generateAIBrief();
    }
  }

  private async generateAIBrief(): Promise<void> {
    if (!this.sourceManager || !this.aiManager) return;
    try {
      const items = await this.sourceManager.fetchAll();
      const brief = await this.aiManager.generateBrief(items);
      this.panelManager?.updatePanel('ai-insights', {
        summary: brief,
        timestamp: new Date().toISOString(),
      });
    } catch (err) {
      console.warn('AI brief generation failed:', err);
    }
  }

  private renderLayerPanel(container: HTMLElement): void {
    if (!this.mapEngine) return;
    const layers = this.mapEngine.getLayerConfigs();

    container.innerHTML = `
      <div class="layer-panel-content">
        <h3>Map Layers</h3>
        ${layers.map(l => `
          <label class="layer-toggle">
            <input type="checkbox" ${l.visible ? 'checked' : ''} data-layer="${l.name}">
            <span>${l.displayName}</span>
          </label>
        `).join('')}
      </div>
    `;

    container.querySelectorAll('input[data-layer]').forEach(input => {
      input.addEventListener('change', (e) => {
        const target = e.target as HTMLInputElement;
        this.mapEngine?.toggleLayer(target.dataset.layer!, target.checked);
      });
    });
  }

  destroy(): void {
    this.sourceManager?.stopAll();
    this.panelManager?.destroy();
    this.mapEngine?.destroy();
  }
}
